all: list tree exec main4 
	gcc -o prog.o main4.o list.o tree.o exec.o

exec: exec.c
	gcc -c exec.c

tree: tree.c
	gcc -c tree.c

list: list.c
	gcc -c list.c

main4: main4.c
	gcc -c main4.c





